---
- name: check input
  fail:
   msg: "please enter valid choices (y/n) next time"
  when :
   - ( {{item}} != "y" )
   - ( {{item}} != "n" )
  with_items:
    - Intelij
    - Eclipse

 # when: ( Intelij != "y" ) and ( Intelij != "n" ) or
 #       ( Eclipse != "y" ) and ( Eclipse != "n" )

- name: print choises
  debug:
   msg: [ "Your choices are :" , "Intelij={{Intelij}}" , "Eclipse={{Eclipse}}" ]

